```{r}
#Date: "09/16/2024"
#Author: "RILEY COGAN"

```

```{r}
# 5.1 Review

library(tidyverse)

# Import data
weather <- read.csv("https://mac-stat.github.io/data/weather_3_locations.csv") |> 
  mutate(date = as.Date(date))  

# Check out the first 6 rows
# What are the units of observation?
head(weather)
# The unit of observation is Australian days.

# How many data points do we have? 
dim(weather)
# We have a total of 2367 data points

# What type of variables do we have?
# We have both categorical and quantitative variables. 

# Example 1

ggplot(weather, aes(x = date, y = temp3pm)) + 
geom_point()

# Example 2

# Plot 1 (no facets & starting from a density plot of temp3pm)
ggplot(weather, aes(x = temp3pm)) + 
  geom_density()

# Plot 2 (no facets or densities)
ggplot(weather, aes(x = temp3pm)) + 
  geom_boxplot()

# Plot 3 (facets)
ggplot(weather, aes(x = temp3pm)) + 
  geom_density() + 
  facet_wrap(~location)
```
```{r}
#
```








```{r}
# Exercise 5.3

# Import and check out data
education <- read.csv("https://mac-stat.github.io/data/sat.csv")
head(education)

#Exercise 1
#- Part A

ggplot(education, aes(y = sat)) + 
  geom_histogram()
```

