---
title: "Activity 02"
Author: "riley Cogan"
Date: "9/13/2024"
---

library(tidyverse)
# Load data
elections <- read.csv("https://mac-stat.github.io/data/election_2020_county.csv")

# Check it out
head(elections)

# Set up the plotting frame
# How does this differ than the frame for our histogram of repub_pct_20 alone?
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16))

# Add a layer of points for each county
# Take note of the geom!
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_point()
  
# Change the shape of the points
# What happens if you change the shape to another number?
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_point(shape = 8)
  
# YOU TRY: Modify the code to make the points "orange"
# NOTE: Try to anticipate if "color" or "fill" will be useful here. Then try both.
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16, color = "orange")) +
  geom_point()
  
# Add a layer that represents each county by the state it's in
# Take note of the geom and the info it needs to run!
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_text(aes(label = state_abbr))
  
# The biggest differences in republican support between '16 and '20 was an increase in support amongst the percentage of people that voted republican, it seems that the dots tend to have shifted upwards in '20. There seems to be a strong, positive relationship between support in '16 and '20. Left leaning states seem to be clustered around the bottom of the line, in areas with the lowest amount of Republican support, whereas the areas that saw the biggest increase where in right leaning states. 

ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_point() +
  geom_smooth()
  
# Removing the individual glyphs

ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_smooth()
  
# Part b
ggplot(elections, aes(y = repub_pct_20, x = repub_pct_16)) +
  geom_point() +
  geom_smooth(method = "lm")
  
# Excersize 5

# Scatterplot of repub_pct_20 vs median_rent
ggplot(elections, aes(y = repub_pct_20, x = median_rent)) + 
  geom_point()
  geom_smooth(method = "lm")


# Scatterplot of repub_pct_20 vs median_age
 ggplot(elections, aes(y = repub_pct_20, x = median_age)) + 
  geom_point()
  geom_smooth(method = "lm") 

# Exercise 6
- scatter plots aren't good plots when there is both a quantitative and a categorical variable present. This is because the different types of variables don't align, and on the axis with the categorical variable, you will be unable to see the range of the variable. 

ggplot(elections, aes(y = repub_pct_20, x = historical)) +
  geom_point()

# Exercise 7

# Side-by-side violin plots
ggplot(elections, aes(y = repub_pct_20, x = historical)) +
  geom_violin()
  
# Side-by-side boxplots (defined below)
ggplot(elections, aes(y = repub_pct_20, x = historical)) +
  geom_boxplot()

# Exercise 8  
 ggplot(elections, aes(x = repub_pct_20)) +
  geom_density() 

# Exercise 9
# Name two "bad" things about this plot
ggplot(elections, aes(x = repub_pct_20, fill = historical)) +
  geom_density()
- The over lapping of the data hides potential trends, and the graph is generally confusing with the labels given. 

# What does scale_fill_manual do?
ggplot(elections, aes(x = repub_pct_20, fill = historical)) +
  geom_density() +
  scale_fill_manual(values = c("blue", "purple", "red"))
  - The scale fill manual allows you to control the colors you use in the plot. 
  
# What does alpha = 0.5 do?
# Play around with different values of alpha, between 0 and 1
ggplot(elections, aes(x = repub_pct_20, fill = historical)) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(values = c("blue", "purple", "red"))
- Alpha changes the transparency of the colors on the plot. 

# What does facet_wrap do?!
ggplot(elections, aes(x = repub_pct_20, fill = historical)) +
  geom_density() +
  scale_fill_manual(values = c("blue", "purple", "red")) +
  facet_wrap(~ historical)
- This creates seperate plots for each variable

# Let's try a similar grouping strategy with a histogram instead of density plot.
# Why is this terrible?
ggplot(elections, aes(x = repub_pct_20, fill = historical)) +
  geom_histogram(color = "white") +
  scale_fill_manual(values = c("blue", "purple", "red"))
- this is terrible becuase it doesn't show any trends and is very confusing in general. 

#Exercise 10
