project:
  type: book
  output-dir: docs

book:
  title: "COMP/STAT112 Notebook"
  author: "Riley Cogan"
  date: "09/03/2024"
  reader-mode: true
  
  chapters:
    - index.qmd

    - part: activities/README.qmd
      chapters: 
      - activities/activity-02.qmd
      - activities/activity-03.qmd
      - activities/05-multivariate.qmd
      - activities/06-spatial.qmd
      - activities/07-effective.qmd
      - activities/08-wrangling.qmd
      - activities/09-wrangling.qmd
      - activities/10-reshaping.qmd
      - activities/11-joining.qmd
     
    
    - part: notes/README.qmd
      chapters: 
      - notes/Journal.qmd
      - notes/note-02.qmd
      
    

format:
  html:
    theme: cosmo
    toc: true
    code-copy: true
    code-line-numbers: true
    code-tools: true

execute:
  cache: true
  freeze: auto
